"""Initial migration

Revision ID: ada267176dd4
Revises: 
Create Date: 2025-05-04 19:21:54.148825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada267176dd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 初始迁移不做任何更改，仅标记当前数据库状态
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 初始迁移不做任何更改，无需回滚操作
    pass
    # ### end Alembic commands ###
