name: Flask App CI/CD

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements/dev.txt
        pip install -r requirements/test.txt
    - name: Lint with flake8
      run: |
        flake8 app/
    - name: Format check with black
      run: |
        black --check app/
    - name: Test with pytest
      run: |
        pytest tests/
      env:
        FLASK_ENV: testing
        SECRET_KEY: github-actions-test-key

  build:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - name: Build application
      run: |
        echo "Building package for version ${GITHUB_REF#refs/tags/}"
        python -m pip install --upgrade pip
        pip install build
        python -m build
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
        body_path: CHANGELOG.md
